"""posts table

Revision ID: b41fd50e92b8
Revises: 9c17ce158294
Create Date: 2020-04-09 14:56:59.919541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41fd50e92b8'
down_revision = '9c17ce158294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.drop_table('users')
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('(NULL)'), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), server_default=sa.text('(NULL)'), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(NULL)'), nullable=True),
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text('(NULL)'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('(NULL)'), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), server_default=sa.text('(NULL)'), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), server_default=sa.text('(NULL)'), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), server_default=sa.text('(NULL)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
